### ISSUE TITLE
除了用class限制和转换数据，还有没有其他方式，比如函数。

### ISSUE THREAD

**Issue by CurryPaste** [phpjavac/vue-cli-plugin-findsoft-basic-v3#11]
就目前项目对class的用法，主要体现在 1转化数据 2限制格式。
[与interface不同，class作为TS的一种变量类型存在于上下文之中，class中可以提供，变量、方法等的具体实现方式等，它的作用不仅仅是约束数据结构。](https://www.cnblogs.com/hlandzpy/p/13213656.html)
可能，会有点浪费。看具体开发情况

**Comment by CurryPaste** [comment]
比如，看某些情况是否可以使用 “继承”，在原本 基础class 上按开发情况进行拓展。
eg：查询条件
基础属性——分页条件，关键字查询。
拓展属性——排序，不同页面的不同条件
好像能少写点代码🤔

**Comment by phpjavac** [comment]
```typescript
class Page {
  pageNo = 1;

  pageSize = 10;

  setPageSize(size: number) {
    this.pageSize = size;
  }

  setPageNo(page: number) {
    this.pageNo = page;
  }
}
class ParamPage extends Page {
  type = '';

  setType(type: string) {
    this.type = type;
  }
}

const pageData = new ParamPage();
pageData.setType('time');
pageData.setPageNo(2);

```

**Comment by CurryPaste** [comment]
我把更改页码的操作放到了父类的构造函数里，然后子类继承的时候，再去执行父类的构造函数😂
```javascript
class BaseSearchClass {
  keyWord?: string;

  pageNo?: number;

  pageSize?: number;

  seqAsc?: boolean;

  seqColumn?: string;

  constructor(data: BaseSearchFace) {
    // base
    this.pageNo = data.pageNo;
    this.pageSize = data.pageSize;

    // 部分接口可能没有 关键字查询
    if(data.keyWord) this.keyWord = data.keyWord;

    // 处理有排序的查询
    if(data.sortDesc !== undefined && data.sortName){
      this.seqAsc = data.sortDesc;
      // 特别的排序字段，交给子类处理。父类只做赋值操作
      this.seqColumn = data.sortName;
    }
  }
}
```

**Comment by CurryPaste** [comment]
@phpjavac 突然发现这个base类可以改进一下
```javascript
class BaseSearchClass {
  keyWord?: string;

  pageNo?: number;

  pageSize?: number;

  seqAsc?: boolean;

  seqColumn?: string;

  // 部分接口可能没有 关键字查询。如果需要就调用方法，传额外的参数接口报错。
  setKeyWord(val: string|undefined) {
    this.keyWord = val;
  }

// 其他参数⭐
  setParams(params:{}){
    Object.assign(this, {...this, ...params})
  }

  constructor(data: BaseSearchFace) {
    // base
    this.pageNo = data.pageNo;
    this.pageSize = data.pageSize;

    // 处理有排序的查询
    if(data.sortDesc !== undefined && data.sortName){
      this.seqAsc = data.sortDesc;
      // 特别的排序字段，交给子类处理。父类只做赋值操作
      this.seqColumn = data.sortName;
    }
  }
}

⭐
const test = new BaseSearchClass(Querydata);
test.setParams({ pageNo: 2, other: 222, params: '123123123' });
console.log(test, 'ttt');
```
通过assign给原本的类添加新的成员，这样应该能 更适用一点😂

**Comment by phpjavac** [comment]
> @phpjavac 突然发现这个base类可以改进一下
> 
> ```js
> class BaseSearchClass {
>   keyWord?: string;
> 
>   pageNo?: number;
> 
>   pageSize?: number;
> 
>   seqAsc?: boolean;
> 
>   seqColumn?: string;
> 
>   // 部分接口可能没有 关键字查询。如果需要就调用方法，传额外的参数接口报错。
>   setKeyWord(val: string|undefined) {
>     this.keyWord = val;
>   }
> 
> // 其他参数⭐
>   setParams(params:{}){
>     Object.assign(this, {...this, ...params})
>   }
> 
>   constructor(data: BaseSearchFace) {
>     // base
>     this.pageNo = data.pageNo;
>     this.pageSize = data.pageSize;
> 
>     // 处理有排序的查询
>     if(data.sortDesc !== undefined && data.sortName){
>       this.seqAsc = data.sortDesc;
>       // 特别的排序字段，交给子类处理。父类只做赋值操作
>       this.seqColumn = data.sortName;
>     }
>   }
> }
> 
> ⭐
> const test = new BaseSearchClass(Querydata);
> test.setParams({ pageNo: 2, other: 222, params: '123123123' });
> console.log(test, 'ttt');
> ```
> 
> 通过assign给原本的类添加新的成员，这样应该能 更适用一点😂

通过Object.assign添加之后访问不能访问属性吧
```
const test = new BaseSearchClass(Querydata);
test.setParams({ pageNo: 2, other: 222, params: '123123123' });
console.log(test, 'ttt');
console.log(test.params) // error BaseSearchClass上无法找到params属性
```

**Comment by CurryPaste** [comment]
嗯，，，，加是加了，不过确实不能访问。
这种形式，后端接口也可以接受
![image](https://user-images.githubusercontent.com/51729441/104149902-fadf1300-5412-11eb-9b4b-7df745e55530.png)

**Comment by phpjavac** [comment]
> 嗯，，，，加是加了，不过确实不能访问。
> 这种形式，后端接口也可以接受
> ![image](https://user-images.githubusercontent.com/51729441/104149902-fadf1300-5412-11eb-9b4b-7df745e55530.png)

extends比较规范吧

**Comment by CurryPaste** [comment]
嗯嗯，现在的用户查询类就是通过继承基础类实现的。
有这个想法的原因是，想尽量少的定义新类，多用实例化和调用方法的方式。
因为很多类可能只会用一次，不知道编译后 代码会不会太多，以后试试

我还是老实用extends吧😂

**Comment by phpjavac** [comment]
> 嗯嗯，现在的用户查询类就是通过继承基础类实现的。
> 有这个想法的原因是，想尽量少的定义新类，多用实例化和调用方法的方式。
> 因为很多类可能只会用一次，不知道编译后 代码会不会太多，以后试试
> 
> 我还是老实用extends吧😂

```
"use strict";

function _typeof(obj) { "@babel/helpers - typeof"; if (typeof Symbol === "function" && typeof Symbol.iterator === "symbol") { _typeof = function _typeof(obj) { return typeof obj; }; } else { _typeof = function _typeof(obj) { return obj && typeof Symbol === "function" && obj.constructor === Symbol && obj !== Symbol.prototype ? "symbol" : typeof obj; }; } return _typeof(obj); }

function _instanceof(left, right) { if (right != null && typeof Symbol !== "undefined" && right[Symbol.hasInstance]) { return !!right[Symbol.hasInstance](left); } else { return left instanceof right; } }

function _inherits(subClass, superClass) { if (typeof superClass !== "function" && superClass !== null) { throw new TypeError("Super expression must either be null or a function"); } subClass.prototype = Object.create(superClass && superClass.prototype, { constructor: { value: subClass, writable: true, configurable: true } }); if (superClass) _setPrototypeOf(subClass, superClass); }

function _setPrototypeOf(o, p) { _setPrototypeOf = Object.setPrototypeOf || function _setPrototypeOf(o, p) { o.__proto__ = p; return o; }; return _setPrototypeOf(o, p); }

function _createSuper(Derived) { var hasNativeReflectConstruct = _isNativeReflectConstruct(); return function _createSuperInternal() { var Super = _getPrototypeOf(Derived), result; if (hasNativeReflectConstruct) { var NewTarget = _getPrototypeOf(this).constructor; result = Reflect.construct(Super, arguments, NewTarget); } else { result = Super.apply(this, arguments); } return _possibleConstructorReturn(this, result); }; }

function _possibleConstructorReturn(self, call) { if (call && (_typeof(call) === "object" || typeof call === "function")) { return call; } return _assertThisInitialized(self); }

function _assertThisInitialized(self) { if (self === void 0) { throw new ReferenceError("this hasn't been initialised - super() hasn't been called"); } return self; }

function _isNativeReflectConstruct() { if (typeof Reflect === "undefined" || !Reflect.construct) return false; if (Reflect.construct.sham) return false; if (typeof Proxy === "function") return true; try { Date.prototype.toString.call(Reflect.construct(Date, [], function () {})); return true; } catch (e) { return false; } }

function _getPrototypeOf(o) { _getPrototypeOf = Object.setPrototypeOf ? Object.getPrototypeOf : function _getPrototypeOf(o) { return o.__proto__ || Object.getPrototypeOf(o); }; return _getPrototypeOf(o); }

function _classCallCheck(instance, Constructor) { if (!_instanceof(instance, Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

function _defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } }

function _createClass(Constructor, protoProps, staticProps) { if (protoProps) _defineProperties(Constructor.prototype, protoProps); if (staticProps) _defineProperties(Constructor, staticProps); return Constructor; }

var BaseSearchClass = /*#__PURE__*/function () {
  _createClass(BaseSearchClass, [{
    key: "setKeyWord",
    // 部分接口可能没有 关键字查询。如果需要就调用方法，传额外的参数接口报错。
    value: function setKeyWord(val) {
      this.keyWord = val;
    } // 其他参数⭐

  }, {
    key: "setParams",
    value: function setParams(params) {
      Object.assign(this, { ...this,
        ...params
      });
    }
  }]);

  function BaseSearchClass(data) {
    _classCallCheck(this, BaseSearchClass);

    // base
    this.pageNo = data.pageNo;
    this.pageSize = data.pageSize; // 处理有排序的查询

    if (data.sortDesc !== undefined && data.sortName) {
      this.seqAsc = data.sortDesc; // 特别的排序字段，交给子类处理。父类只做赋值操作

      this.seqColumn = data.sortName;
    }
  }

  return BaseSearchClass;
}();

var test = new BaseSearchClass(Querydata);
test.setParams({
  pageNo: 2,
  other: 222,
  params: '123123123'
});
console.log(test, 'ttt');

var BaseSearchClassTow = /*#__PURE__*/function () {
  _createClass(BaseSearchClassTow, [{
    key: "setKeyWord",
    // 部分接口可能没有 关键字查询。如果需要就调用方法，传额外的参数接口报错。
    value: function setKeyWord(val) {
      this.keyWord = val;
    }
  }]);

  function BaseSearchClassTow(data) {
    _classCallCheck(this, BaseSearchClassTow);

    // base
    this.pageNo = data.pageNo;
    this.pageSize = data.pageSize; // 处理有排序的查询

    if (data.sortDesc !== undefined && data.sortName) {
      this.seqAsc = data.sortDesc; // 特别的排序字段，交给子类处理。父类只做赋值操作

      this.seqColumn = data.sortName;
    }
  }

  return BaseSearchClassTow;
}();

var ParamsBaseSearchClassTow = /*#__PURE__*/function (_BaseSearchClassTow) {
  _inherits(ParamsBaseSearchClassTow, _BaseSearchClassTow);

  var _super = _createSuper(ParamsBaseSearchClassTow);

  function ParamsBaseSearchClassTow(data) {
    _classCallCheck(this, ParamsBaseSearchClassTow);

    return _super.call(this, data);
  }

  _createClass(ParamsBaseSearchClassTow, [{
    key: "setOther",
    value: function setOther(other) {
      this.other = other;
    }
  }, {
    key: "setParams",
    value: function setParams(params) {
      this.params = params;
    }
  }]);

  return ParamsBaseSearchClassTow;
}(BaseSearchClassTow);

var test1 = new BaseSearchClassTow(Querydata);
test1.setOther(222);
test1.setParams("111111");
```

**Comment by phpjavac** [comment]
> > 嗯嗯，现在的用户查询类就是通过继承基础类实现的。
> > 有这个想法的原因是，想尽量少的定义新类，多用实例化和调用方法的方式。
> > 因为很多类可能只会用一次，不知道编译后 代码会不会太多，以后试试
> > 我还是老实用extends吧😂
> 
> ```
> "use strict";
> 
> function _typeof(obj) { "@babel/helpers - typeof"; if (typeof Symbol === "function" && typeof Symbol.iterator === "symbol") { _typeof = function _typeof(obj) { return typeof obj; }; } else { _typeof = function _typeof(obj) { return obj && typeof Symbol === "function" && obj.constructor === Symbol && obj !== Symbol.prototype ? "symbol" : typeof obj; }; } return _typeof(obj); }
> 
> function _instanceof(left, right) { if (right != null && typeof Symbol !== "undefined" && right[Symbol.hasInstance]) { return !!right[Symbol.hasInstance](left); } else { return left instanceof right; } }
> 
> function _inherits(subClass, superClass) { if (typeof superClass !== "function" && superClass !== null) { throw new TypeError("Super expression must either be null or a function"); } subClass.prototype = Object.create(superClass && superClass.prototype, { constructor: { value: subClass, writable: true, configurable: true } }); if (superClass) _setPrototypeOf(subClass, superClass); }
> 
> function _setPrototypeOf(o, p) { _setPrototypeOf = Object.setPrototypeOf || function _setPrototypeOf(o, p) { o.__proto__ = p; return o; }; return _setPrototypeOf(o, p); }
> 
> function _createSuper(Derived) { var hasNativeReflectConstruct = _isNativeReflectConstruct(); return function _createSuperInternal() { var Super = _getPrototypeOf(Derived), result; if (hasNativeReflectConstruct) { var NewTarget = _getPrototypeOf(this).constructor; result = Reflect.construct(Super, arguments, NewTarget); } else { result = Super.apply(this, arguments); } return _possibleConstructorReturn(this, result); }; }
> 
> function _possibleConstructorReturn(self, call) { if (call && (_typeof(call) === "object" || typeof call === "function")) { return call; } return _assertThisInitialized(self); }
> 
> function _assertThisInitialized(self) { if (self === void 0) { throw new ReferenceError("this hasn't been initialised - super() hasn't been called"); } return self; }
> 
> function _isNativeReflectConstruct() { if (typeof Reflect === "undefined" || !Reflect.construct) return false; if (Reflect.construct.sham) return false; if (typeof Proxy === "function") return true; try { Date.prototype.toString.call(Reflect.construct(Date, [], function () {})); return true; } catch (e) { return false; } }
> 
> function _getPrototypeOf(o) { _getPrototypeOf = Object.setPrototypeOf ? Object.getPrototypeOf : function _getPrototypeOf(o) { return o.__proto__ || Object.getPrototypeOf(o); }; return _getPrototypeOf(o); }
> 
> function _classCallCheck(instance, Constructor) { if (!_instanceof(instance, Constructor)) { throw new TypeError("Cannot call a class as a function"); } }
> 
> function _defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } }
> 
> function _createClass(Constructor, protoProps, staticProps) { if (protoProps) _defineProperties(Constructor.prototype, protoProps); if (staticProps) _defineProperties(Constructor, staticProps); return Constructor; }
> 
> var BaseSearchClass = /*#__PURE__*/function () {
>   _createClass(BaseSearchClass, [{
>     key: "setKeyWord",
>     // 部分接口可能没有 关键字查询。如果需要就调用方法，传额外的参数接口报错。
>     value: function setKeyWord(val) {
>       this.keyWord = val;
>     } // 其他参数⭐
> 
>   }, {
>     key: "setParams",
>     value: function setParams(params) {
>       Object.assign(this, { ...this,
>         ...params
>       });
>     }
>   }]);
> 
>   function BaseSearchClass(data) {
>     _classCallCheck(this, BaseSearchClass);
> 
>     // base
>     this.pageNo = data.pageNo;
>     this.pageSize = data.pageSize; // 处理有排序的查询
> 
>     if (data.sortDesc !== undefined && data.sortName) {
>       this.seqAsc = data.sortDesc; // 特别的排序字段，交给子类处理。父类只做赋值操作
> 
>       this.seqColumn = data.sortName;
>     }
>   }
> 
>   return BaseSearchClass;
> }();
> 
> var test = new BaseSearchClass(Querydata);
> test.setParams({
>   pageNo: 2,
>   other: 222,
>   params: '123123123'
> });
> console.log(test, 'ttt');
> 
> var BaseSearchClassTow = /*#__PURE__*/function () {
>   _createClass(BaseSearchClassTow, [{
>     key: "setKeyWord",
>     // 部分接口可能没有 关键字查询。如果需要就调用方法，传额外的参数接口报错。
>     value: function setKeyWord(val) {
>       this.keyWord = val;
>     }
>   }]);
> 
>   function BaseSearchClassTow(data) {
>     _classCallCheck(this, BaseSearchClassTow);
> 
>     // base
>     this.pageNo = data.pageNo;
>     this.pageSize = data.pageSize; // 处理有排序的查询
> 
>     if (data.sortDesc !== undefined && data.sortName) {
>       this.seqAsc = data.sortDesc; // 特别的排序字段，交给子类处理。父类只做赋值操作
> 
>       this.seqColumn = data.sortName;
>     }
>   }
> 
>   return BaseSearchClassTow;
> }();
> 
> var ParamsBaseSearchClassTow = /*#__PURE__*/function (_BaseSearchClassTow) {
>   _inherits(ParamsBaseSearchClassTow, _BaseSearchClassTow);
> 
>   var _super = _createSuper(ParamsBaseSearchClassTow);
> 
>   function ParamsBaseSearchClassTow(data) {
>     _classCallCheck(this, ParamsBaseSearchClassTow);
> 
>     return _super.call(this, data);
>   }
> 
>   _createClass(ParamsBaseSearchClassTow, [{
>     key: "setOther",
>     value: function setOther(other) {
>       this.other = other;
>     }
>   }, {
>     key: "setParams",
>     value: function setParams(params) {
>       this.params = params;
>     }
>   }]);
> 
>   return ParamsBaseSearchClassTow;
> }(BaseSearchClassTow);
> 
> var test1 = new BaseSearchClassTow(Querydata);
> test1.setOther(222);
> test1.setParams("111111");
> ```
```
class BaseSearchClass {
  keyWord?: string;

  pageNo?: number;

  pageSize?: number;

  seqAsc?: boolean;

  seqColumn?: string;

  // 部分接口可能没有 关键字查询。如果需要就调用方法，传额外的参数接口报错。
  setKeyWord(val: string|undefined) {
    this.keyWord = val;
  }

	// 其他参数⭐
  setParams(params:{}){
    Object.assign(this, {...this, ...params})
  }

  constructor(data: BaseSearchFace) {
    // base
    this.pageNo = data.pageNo;
    this.pageSize = data.pageSize;

    // 处理有排序的查询
    if(data.sortDesc !== undefined && data.sortName){
      this.seqAsc = data.sortDesc;
      // 特别的排序字段，交给子类处理。父类只做赋值操作
      this.seqColumn = data.sortName;
    }
  }
}

const test = new BaseSearchClass(Querydata);
test.setParams({ pageNo: 2, other: 222, params: '123123123' });
console.log(test, 'ttt');

class BaseSearchClassTow {
  keyWord?: string;

  pageNo?: number;

  pageSize?: number;

  seqAsc?: boolean;

  seqColumn?: string;

  // 部分接口可能没有 关键字查询。如果需要就调用方法，传额外的参数接口报错。
  setKeyWord(val: string|undefined) {
    this.keyWord = val;
  }


  constructor(data: BaseSearchFace) {
    // base
    this.pageNo = data.pageNo;
    this.pageSize = data.pageSize;

    // 处理有排序的查询
    if(data.sortDesc !== undefined && data.sortName){
      this.seqAsc = data.sortDesc;
      // 特别的排序字段，交给子类处理。父类只做赋值操作
      this.seqColumn = data.sortName;
    }
  }
}

class ParamsBaseSearchClassTow extends BaseSearchClassTow{
  
  other:Number;
  params;
  constructor(data: BaseSearchFace) {
    super(data);
  }
  
  setOther(other){
    this.other = other;
  }
  setParams(params){
    this.params = params;
  }
}
const test1 = new BaseSearchClassTow(Querydata);
test1.setOther(222);
test1.setParams("111111");
```

**Comment by CurryPaste** [comment]
[用在线转换试了下，感觉extends多的寥寥](https://babeljs.io/repl/#?browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=Q&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=es2015%2Creact%2Cstage-2%2Ctypescript&prettier=false&targets=&version=7.12.12&externalPlugins=)
