### ISSUE TITLE
mock api完善

### ISSUE THREAD

**Issue by phpjavac** [phpjavac/vue-cli-plugin-findsoft-basic-v3#21]

**Comment by CurryPaste** [comment]
1. vue add 对应配置文件的完善（css,types,package）
2. header组件样式按设计的来
3. 基础组件mock完善，增加mock专用的运行环境 [环境变量](https://cli.vuejs.org/zh/guide/mode-and-env.html#%E6%A8%A1%E5%BC%8F)
