### ISSUE TITLE
是否需要添加版本查看功能

### ISSUE THREAD

**Issue by yinzhenyu-su** [phpjavac/vue-cli-plugin-findsoft-basic-v3#52]
![控制台显示打包版本](https://i.loli.net/2021/05/10/XJsCO9gNaRxZiwl.png)

好处是可以在控制台显示打包版本，方便测试确认当前版本，也可以根据前端svn版本号判断页面是否是缓存从而刷新页面，坏处是会多产生两个请求（分别获取前端和后端版本号）

实现逻辑是在打包时生成 version.json 文件保存打包时的版本号，页面刷新时请求该文件获取版本号。

**Comment by phpjavac** [comment]
之前项目发布时好像会没有生成version.json 导致get404 需要注意一下
